# Overview

The purpose of this notebook is to explore the neww addtional data that will be use to expand the household data across Miami dataset

In [7]:
# Load the datasets

import pandas as pd

from pathlib import Path

# Support running the notebook with either the repository root or notebooks/ as cwd.
DATA_DIR_CANDIDATES = (Path.cwd() / "data", Path.cwd().parent / "data")
DATA_DIR = next((path for path in DATA_DIR_CANDIDATES if path.is_dir()), None)
if DATA_DIR is None:
    raise FileNotFoundError(
        "Could not find the project's data directory. Run this notebook from the repository root or notebooks/."
    )

DATASETS = {
    "home-values": DATA_DIR / "Zip_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv",
    "rental": DATA_DIR / "Zip_zori_uc_sfrcondomfr_sm_month.csv",
}
OUTPUT_DATASETS = {
    "home-values": DATA_DIR / "Miami_home_values.csv",
    "rental": DATA_DIR / "Miami_rental_values.csv",
}
for name, source_path in DATASETS.items():
    source_df = pd.read_csv(source_path)
    miami_df = source_df.loc[
        (source_df["City"] == "Miami") & (source_df["State"] == "FL")
    ].copy()
    miami_df.to_csv(OUTPUT_DATASETS[name], index=False)

# Remove monthly price columns dated from 2000 through 2024, inclusive.
for name, output_path in OUTPUT_DATASETS.items():
    filtered_df = pd.read_csv(output_path)
    price_columns_to_drop = [
        column
        for column in filtered_df.columns
        if column[:4].isdigit() and 2000 <= int(column[:4]) <= 2025
    ]
    filtered_df.drop(columns=price_columns_to_drop).to_csv(output_path, index=False)

# Reload the saved files and display the requested details.
filtered_datasets = {
    name: pd.read_csv(path)
    for name, path in OUTPUT_DATASETS.items()
}

for name, filtered_df in filtered_datasets.items():
    print(f"{name}: {OUTPUT_DATASETS[name].name}")
    print("Column names:")
    print(filtered_df.columns.tolist())
    print("Head:")
    display(filtered_df.head())
    print(f"Shape: {filtered_df.shape}")
    print()

home-values: Miami_home_values.csv
Column names:
['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName', 'State', 'City', 'Metro', 'CountyName', '2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30', '2026-05-31', '2026-06-30', '2026-07-31', '2026-08-31']
Head:

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31,2026-08-31
0,72479,532,33177,zip,FL,FL,Miami,"Miami-Fort Lauderdale-Pompano Beach, FL",Miami-Dade County,572001.396142,572600.659570,572768.260095,572439.143081,572045.092820,571413.658941,571333.660763,571878.857601
1,72428,719,33125,zip,FL,FL,Miami,"Miami-Fort Lauderdale-Pompano Beach, FL",Miami-Dade County,458810.786391,458821.311976,459090.730605,458379.150299,457880.575590,458152.983552,459977.688607,462144.109086
2,72478,911,33176,zip,FL,FL,Miami,"Miami-Fort Lauderdale-Pompano Beach, FL",Miami-Dade County,619516.277251,621550.059900,623094.569954,623496.917427,623603.630863,623471.991293,624095.640402,625867.558301
3,72468,1012,33165,zip,FL,FL,Miami,"Miami-Fort Lauderdale-Pompano Beach, FL",Miami-Dade County,673162.864323,674929.075867,676156.501777,676094.916531,676228.455622,676771.339057,678472.560963,680797.179702
4,72494,1186,33193,zip,FL,FL,Miami,"Miami-Fort Lauderdale-Pompano Beach, FL",Miami-Dade County,442355.664123,441797.636349,441521.148034,441183.154906,441067.989391,441041.959003,441580.978071,442117.321392

Shape: (30, 17)

rental: Miami_rental_values.csv
Column names:
['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName', 'State', 'City', 'Metro', 'CountyName', '2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30', '2026-05-31', '2026-06-30', '2026-07-31', '2026-08-31']
Head:

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31,2026-08-31
0,72479,532,33177,zip,FL,FL,Miami,"Miami-Fort Lauderdale-Pompano Beach, FL",Miami-Dade County,2773.309455,2774.921234,2810.792150,2853.532707,2873.582158,2831.216533,2837.589671,2818.554226
1,72428,719,33125,zip,FL,FL,Miami,"Miami-Fort Lauderdale-Pompano Beach, FL",Miami-Dade County,2329.948258,2343.501323,2338.540953,2343.803702,2367.529247,2359.229336,2372.197132,2379.843835
2,72478,911,33176,zip,FL,FL,Miami,"Miami-Fort Lauderdale-Pompano Beach, FL",Miami-Dade County,2247.329050,2237.606074,2271.559104,2252.734700,2264.678650,2275.870591,2309.894964,2303.963816
3,72468,1012,33165,zip,FL,FL,Miami,"Miami-Fort Lauderdale-Pompano Beach, FL",Miami-Dade County,3350.049412,3278.916322,3243.497895,3190.257233,3174.586655,3179.622522,3289.030200,3247.500000
4,72494,1186,33193,zip,FL,FL,Miami,"Miami-Fort Lauderdale-Pompano Beach, FL",Miami-Dade County,2382.909949,2362.085749,2324.695703,2319.349149,2319.952724,2359.771817,2372.358258,2374.074074

Shape: (29, 17)

For every recommended ZIP, show:
1. Typical rent
2. Difference from the user’s budget
3. Estimated commute
4. Nearby transit options
5. Rent trend
6. Flood-risk information
7. Explanation of why it was recommended

Question to the person
1. Should we include transportation and flood risk information for the recommendation engine 
2. Does